{
  flake.nixosModules.laptopHardware = { config, lib, pkgs, modulesPath, ... }: {
    # Do not modify this file!  It was generated by 'nixos-generate-config'
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
    
    boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];
    
    fileSystems."/" =
    { device = "/dev/disk/by-uuid/91edb980-2c89-4206-9bbd-5ec1454b58de";
            fsType = "btrfs";
            options = [ "subvol=root" ];
    };
    
    fileSystems."/home" =
    { device = "/dev/disk/by-uuid/91edb980-2c89-4206-9bbd-5ec1454b58de";
            fsType = "btrfs";
            options = [ "subvol=home" ];
    };
    
    fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/91edb980-2c89-4206-9bbd-5ec1454b58de";
            fsType = "btrfs";
            options = [ "subvol=nix" ];
    };
    
    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9639-96EF";
            fsType = "vfat";
            options = [ "fmask=0022" "dmask=0022" ];
    };
    
    swapDevices = [ ];
    
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  };
}
