{
  flake.nixosModules.dns-hardware = { config, lib, pkgs, modulesPath, ... }: {
    # Do not modify this file!  It was generated by 'nixos-generate-config'
    # and may be overwritten by future invocations.  Please make changes
    # to your configuration instead.
    imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
    
    boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];
    
    # Example VM disk configuration - adjust as needed
    # fileSystems."/" =
    # { device = "/dev/disk/by-uuid/...";
    #   fsType = "ext4";
    # };
    # 
    # fileSystems."/boot" =
    # { device = "/dev/disk/by-uuid/...";
    #   fsType = "vfat";
    # };
    
    swapDevices = [ ];
    
    # VM platform
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  };
}