{
  flake.nixosModules.thinkbook-plus-hardware = { config, lib, pkgs, modulesPath, ... }: {
    # Do not modify this file!  It was generated by 'nixos-generate-config'
    # and may be overwritten by future invocations.  Please make changes
    # to your configuration instead.
    imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
    
    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ]; # Adjust based on your CPU
    boot.extraModulePackages = [ ];
    
    # Add your disk configurations here
    # Example:
    # fileSystems."/" =
    # { device = "/dev/disk/by-uuid/...";
    #   fsType = "ext4";
    # };
    
    # fileSystems."/boot" =
    # { device = "/dev/disk/by-uuid/...";
    #   fsType = "vfat";
    # };
    
    swapDevices = [ ];
    
    # Change according to your system
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  };
}